//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingJScript.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Style
    {
        public int StyleID { get; set; }
        public string Color { get; set; }
        public string StyleType { get; set; }
        public string Photo { get; set; }
        public int ClothingID { get; set; }
        public string Review { get; set; }
    
        public virtual Clothing Clothing { get; set; }
    }
}
